// <auto-generated />
using System;
using Finis.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finis.Api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20250828212808_Cartao")]
    partial class Cartao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finis.Domain.Models.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DtCadastro")
                        .HasColumnType("date");

                    b.Property<bool>("FlVendido")
                        .HasColumnType("bit");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAtivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAtivoCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QtdCotas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SeguimentoAtivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoAtivoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoAtivoId");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("Finis.Domain.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DtCadastro")
                        .HasColumnType("date");

                    b.Property<string>("InstituicaoBancaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCartao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("Finis.Domain.Models.CompraAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtivoId")
                        .HasColumnType("int");

                    b.Property<string>("Corretora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DtCompra")
                        .HasColumnType("date");

                    b.Property<decimal>("EstimativaVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estrategia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlBolsa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FlVendido")
                        .HasColumnType("bit");

                    b.Property<string>("NomeAtivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QtdCotas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCota")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.ToTable("CompraAtivos");
                });

            modelBuilder.Entity("Finis.Domain.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaPaiId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorSaldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("Finis.Domain.Models.HistoricoAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtivoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DtHistorico")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.ToTable("HistoricoAtivos");
                });

            modelBuilder.Entity("Finis.Domain.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoMovimentacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DtMovimentacao")
                        .HasColumnType("date");

                    b.Property<int>("FlMovimentacao")
                        .HasColumnType("int");

                    b.Property<string>("TipoGasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorMovimentacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Movimentacaoes");
                });

            modelBuilder.Entity("Finis.Domain.Models.Rendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnoRendimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AtivoId")
                        .HasColumnType("int");

                    b.Property<string>("Corretora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DtRendimento")
                        .HasColumnType("date");

                    b.Property<string>("FlBolsa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MesRendimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QtdCotas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRendimento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRendimentoReais")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.ToTable("Rendimentos");
                });

            modelBuilder.Entity("Finis.Domain.Models.TipoAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TipoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoAtivos");
                });

            modelBuilder.Entity("Finis.Domain.Models.VendaAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtivoId")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DtVenda")
                        .HasColumnType("date");

                    b.Property<string>("FlBolsa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QtdCotas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTaxas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLucro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLucroReais")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRecebido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("VendaAtivos");
                });

            modelBuilder.Entity("Finis.Domain.Models.Ativo", b =>
                {
                    b.HasOne("Finis.Domain.Models.TipoAtivo", "TipoAtivo")
                        .WithMany("Ativos")
                        .HasForeignKey("TipoAtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAtivo");
                });

            modelBuilder.Entity("Finis.Domain.Models.CompraAtivo", b =>
                {
                    b.HasOne("Finis.Domain.Models.Ativo", "Ativo")
                        .WithMany("CompraAtivos")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("Finis.Domain.Models.HistoricoAtivo", b =>
                {
                    b.HasOne("Finis.Domain.Models.Ativo", "Ativo")
                        .WithMany("HistoricoAtivos")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("Finis.Domain.Models.Rendimento", b =>
                {
                    b.HasOne("Finis.Domain.Models.Ativo", "Ativo")
                        .WithMany("Rendimentos")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("Finis.Domain.Models.Ativo", b =>
                {
                    b.Navigation("CompraAtivos");

                    b.Navigation("HistoricoAtivos");

                    b.Navigation("Rendimentos");
                });

            modelBuilder.Entity("Finis.Domain.Models.TipoAtivo", b =>
                {
                    b.Navigation("Ativos");
                });
#pragma warning restore 612, 618
        }
    }
}
