// <auto-generated />
using System;
using Finis.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finis.Api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20250724001450_alterarQTDCotas")]
    partial class alterarQTDCotas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finis.Domain.Models.Ativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DtCadastro")
                        .HasColumnType("date");

                    b.Property<bool>("FlVendido")
                        .HasColumnType("bit");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAtivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAtivoCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QtdCotas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SeguimentoAtivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoAtivoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoAtivoId");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("Finis.Domain.Models.CompraAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtivoId")
                        .HasColumnType("int");

                    b.Property<string>("Corretora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DtCompra")
                        .HasColumnType("date");

                    b.Property<decimal>("EstimativaVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estrategia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlBolsa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FlVendido")
                        .HasColumnType("bit");

                    b.Property<string>("NomeAtivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdCotas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorCota")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtivoId");

                    b.ToTable("CompraAtivos");
                });

            modelBuilder.Entity("Finis.Domain.Models.TipoAtivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TipoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoAtivos");
                });

            modelBuilder.Entity("Finis.Domain.Models.Ativo", b =>
                {
                    b.HasOne("Finis.Domain.Models.TipoAtivo", "TipoAtivo")
                        .WithMany("Ativos")
                        .HasForeignKey("TipoAtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoAtivo");
                });

            modelBuilder.Entity("Finis.Domain.Models.CompraAtivo", b =>
                {
                    b.HasOne("Finis.Domain.Models.Ativo", "Ativo")
                        .WithMany("CompraAtivos")
                        .HasForeignKey("AtivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("Finis.Domain.Models.Ativo", b =>
                {
                    b.Navigation("CompraAtivos");
                });

            modelBuilder.Entity("Finis.Domain.Models.TipoAtivo", b =>
                {
                    b.Navigation("Ativos");
                });
#pragma warning restore 612, 618
        }
    }
}
